### ISSUE TITLE
Build failing for rav1e enabling hawktracer on ubuntu aarch64 device

### ISSUE THREAD

**Issue by vaishnavsivadas** [AlexEne/rust_hawktracer#22]
I tried building rav1e with hawktracer support but it's giving me a mismatched types error. I tried building it with adding "generate_bindings" along with "profiling_enabled" in features for rust_hawktracer in Cargo.toml, but the error still persists. Attaching the error log here: 
```
error[E0308]: mismatched types
 --> /home/vaishnav/.cargo/registry/src/github.com-1ecc6299db9ec823/rust_hawktracer_sys-0.2.0/src/internals/scoped_tracepoint.rs:8:73
  |
8 |             ht_feature_callstack_start_string(ht_global_timeline_get(), name);
  |                                                                         ^^^^ expected u8, found i8
  |
  = note: expected type `*const u8`
             found type `*mut i8`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `rust_hawktracer_sys`.
```

**Comment by AlexEne** [comment]
Oh no, sorry about that. I will try to patch it :(. It's strange as CI passes on ubuntu 16&18.
Actually what makes it even worse is that if I change it to be *mut u8, i get the following: 
![image](https://user-images.githubusercontent.com/5849037/69104290-b1d63d80-0a5f-11ea-8a61-f8960f4dd9ee.png)

**Comment by AlexEne** [comment]
Sorry about this, it should work now. Please run the following command in order to fetch 0.2.1 of rust_hawktracer_sys. 
`cargo update -p rust_hawktracer_sys`

On new instances, where `cargo.lock` isn't present thsi should just work on rust_hawktracer 0.5.0^

**Comment by vaishnavsivadas** [comment]
The build is working fine now, thank you for the response.
